[project]
name = "playground-rag"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ricardo Trujillo", email = "rtrujillor@hotmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
playground-rag = "playground_rag:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
